### ISSUE TITLE
Sensors

### ISSUE THREAD

**Issue by asifma** [kimlood/MMM-telldusLive#2]
Hi! Love this module. Would be great if you could include Sensors also? 

By using cloud.getSensors

Best regards
Asif

**Comment by kimlood** [comment]
Hi, 
Yes that's an great idea, but should sensor values be added to the same position or in it's own container?

**Comment by asifma** [comment]
I think it would be nicer to have it in its own container if possible, with a nice icon of "temperature" or "humidity" 

![image](https://cloud.githubusercontent.com/assets/27285709/24961456/1f95dc5e-1f99-11e7-992f-e417bc8288e4.png)

**Comment by asifma** [comment]
Did you come up with something :)?

**Comment by kimlood** [comment]
Havent have time to look at it, but as soon as I have, this will be implemented.

**Comment by asifma** [comment]
Tja, jag försöker få till det. Inte lätt alltså. Hittat en funktion som fungerar.  Lagt till den i node_helper.js
Variablerna som spottas ut är korrekta. Nu är frågan hur jag ska lagra allt i en array och sedan publicera det. Har du tid att sitta ihop ngn kväll remote :)?

   cloud.getSensors(function(err, sensors) {
    var f, i;

    if (!!err) return console.log('getSensors: ' + err.message);

    f = function(offset, p, s) {
      return function(err, sensor) {
        var i, prop, props, type;

        if (!!err) return console.log(s + ' id=' + p.id + ': ' + err.message);

        console.log('sensor #' + offset + ' ' + s + ': '); console.log(sensor);
        props =  { temp     : [ 'temperature', 'celcius',    'meteo' ]
                 , humidity : [ 'humidity',    'percentage', 'meteo' ]
                 };

        type = null;
        for (i = 0; i < sensor.data.length; i++) {
          type = props[sensor.data[i].name];
          if (!!type) break;
        }
        if (!type) return;

        console.log('/device/climate/' + (sensor.protocol || 'telldus') + '/' + type[2]);
        console.log('    uuid=teldus:' + sensor.id);
        console.log('    name: ' + sensor.name);
        console.log('    status: ' + (p.online === '1' ? 'present' : 'absent'));
        console.log('    lastSample: ' + sensor.lastUpdated * 1000);
        console.log('    info:');
        for (i = 0; i < sensor.data.length; i++) {
          prop =  props[sensor.data[i].name];
          if (prop) console.log('      ' + prop[0] + ': "' + prop[1] + '"');
        }
        console.log('    values:');
        for (i = 0; i < sensor.data.length; i++) {
          prop =  props[sensor.data[i].name];
          if (prop) console.log('      ' + prop[0] + ': ' + sensor.data[i].value);
        }
        console.log('');
      };
    };

    for (i = 0; i < sensors.length; i++) 
		cloud.getSensorInfo(sensors[i], f(i, sensors[i], 'getSensorInfo'));
  })

**Comment by kimlood** [comment]
Hi, did you manage to implement this or do you still need some assistance?

**Comment by asifma** [comment]
Hi, No I haven't looked in to it. It would be nice to do it together if possible? Have a session on Skype.

**Comment by farna87** [comment]
I have made a fork wich have sensors included.
https://github.com/farna87/MMM-telldusLive

I have made a Pull Request on the code and I will gladly help you with the project @kimlood  if its ok with you?

The sensor code has support for diffrent kind of settings via config.js
```javascript
{
	module: 'MMM-telldusLive',
	header: 'My Home',
	position: 'top_right', 
	config: {
		publicKey: '<public_key>', 
		privateKey: '<private_key>', 
		token: '<token>', 
		tokenSecret: '<token_secret>',
		sensors: {
			includeIgnored: <bool>,
			showAll: <bool>,
			oneRow: <bool>,
			showDataFullNames: <bool>,
			hideDataNames: <bool>,
			hideDataIcons: <bool>,
			sensorsToShow: <object>
		} 
	}
}
```

**Comment by kimlood** [comment]
Thanks @farna87!
