### ISSUE TITLE
Stopped loading after last update

### ISSUE THREAD

**Issue by siggmur** [kimlood/MMM-telldusLive#4]
No changes to the config, it only states loading after the last MM update

**Comment by zumpen** [comment]
Bumping this, have somone solve this problem?

**Comment by fredriklunde** [comment]
Had the same issue, apparently had something to do with the api endpoint. When going into node_modules/telldus-live and in telldus-live.js changing all occurances of https to http, it started to work...

**Comment by kimlood** [comment]
@fredriklunde sounds like a update/new install of the dependencies would do the trick as well?

**Comment by kimlood** [comment]
> Had the same issue, apparently had something to do with the api endpoint. When going into node_modules/telldus-live and in telldus-live.js changing all occurances of https to http, it started to work...

Sounds like a update/new install of the dependencies would do the trick as well?

**Comment by fredriklunde** [comment]
> > Had the same issue, apparently had something to do with the api endpoint. When going into node_modules/telldus-live and in telldus-live.js changing all occurances of https to http, it started to work...
> 
> Sounds like a update/new install of the dependencies would do the trick as well?

Probably not since https://www.npmjs.com/package/telldus-live has not been updated for the last few years. But there might be another solution to this since it has worked previously. Doing what I did is just a work around, it will break after running npm install

**Comment by kimlood** [comment]
> > > Had the same issue, apparently had something to do with the api endpoint. When going into node_modules/telldus-live and in telldus-live.js changing all occurances of https to http, it started to work...
> > 
> > 
> > Sounds like a update/new install of the dependencies would do the trick as well?
> 
> Probably not since https://www.npmjs.com/package/telldus-live has not been updated for the last few years. But there might be another solution to this since it has worked previously. Doing what I did is just a work around, it will break after running npm install

Oh, thought that was fixed when looking into the source code: 
```javascript
self.oauth._performSecureRequest(self.token, self.tokenSecret, method, 'https://api.telldus.com/json' + path, null, json,
                                   !!json ? 'application/json' : null, function(err, body, response) {
      var expected = { GET    : [ 200 ]
                     , PUT    : [ 200 ]
                     , POST   : [ 200, 201, 202 ]
                     , DELETE : [ 200 ]
                     }[method];
```

**Comment by fredriklunde** [comment]
> > > > Had the same issue, apparently had something to do with the api endpoint. When going into node_modules/telldus-live and in telldus-live.js changing all occurances of https to http, it started to work...
> > > 
> > > 
> > > Sounds like a update/new install of the dependencies would do the trick as well?
> > 
> > 
> > Probably not since https://www.npmjs.com/package/telldus-live has not been updated for the last few years. But there might be another solution to this since it has worked previously. Doing what I did is just a work around, it will break after running npm install
> 
> Oh, thought that was fixed when looking into the source code:
> 
> ```js
> self.oauth._performSecureRequest(self.token, self.tokenSecret, method, 'https://api.telldus.com/json' + path, null, json,
>                                    !!json ? 'application/json' : null, function(err, body, response) {
>       var expected = { GET    : [ 200 ]
>                      , PUT    : [ 200 ]
>                      , POST   : [ 200, 201, 202 ]
>                      , DELETE : [ 200 ]
>                      }[method];
> ```

What got it working for me was changing https to http
